Testes da aplicação - Rota GET
andressa-mb/ecommerce-api pull request #12
Opened 2024-12-17 20:52 UTC by andressa-mb

* Installation of Jest and supertest
* Create a mock to test
* Tests of route GET

2024-12-26 23:42 UTC, Luiz-Cruz commented on api/api.js
> +        console.log(`Servidor escutando na porta ${port}`);
Em inglês sempre

2024-12-26 23:42 UTC, Luiz-Cruz commented on api/api.js
> +        connectTimeoutMS: 10000, // tenta a conexão por até 10 segundos
Remover comentários

2024-12-26 23:42 UTC, Luiz-Cruz commented on api/api.js
> +console.log("ESTOU NA API");
apagar

2024-12-26 23:43 UTC, Luiz-Cruz commented on src/features/orders/mockData.js
> +const orders = [
tem como colocar isso dentro do arquivo de teste?
não é necessário separar em um arquivo novo dentro da pasta features

2024-12-26 23:43 UTC, Luiz-Cruz commented on src/features/orders/order.controller.js
> +      res.status(500).json({ message: `Erro ao buscar orders. Error: ${err}`});
Inglês

2024-12-26 23:44 UTC, Luiz-Cruz commented on test/orders.test.js
> +  // Antes de cada teste, define o comportamento do mock
apagar

2024-12-26 23:44 UTC, Luiz-Cruz commented on test/orders.test.js
> +      // Configura o mock para retornar os dados do mockOrders
apagar

2024-12-26 23:44 UTC, Luiz-Cruz commented on test/orders.test.js
> +    console.log("ESTOU EM TESTS E VOU BUSCAR OS PEDIDOS");
.

2024-12-26 23:44 UTC, Luiz-Cruz commented on test/orders.test.js
> +      console.log(` OLHA O RESSS: ${JSON.stringify(res.body, null, 2)} `);
.

2024-12-30 17:46 UTC, Luiz-Cruz commented on test/mockData.js
> +const orders = [
esse dado você pode deixar dentro do mesmo arquivo do teste, não é necessário colocar ele em um arquivo separado

2024-12-30 17:47 UTC, Luiz-Cruz commented on test/orders.test.js
> +    it('deve retornar a lista de pedidos', async () => {
poderia adicionar também o que deve ocorrer se a função que pega os dados do banco gerar um erro

2024-12-30 17:48 UTC, Luiz-Cruz commented on test/orders.test.js
> +    it('deve retornar a lista de pedidos', async () => {
eu simularia um caso de sucesso e um de erro

2024-12-30 17:49 UTC, Luiz-Cruz commented on test/orders.test.js
> +    it('deve retornar a lista de pedidos', async () => {
o de sucesso retorna 200 OK, e o de erro deveria retornar o 500

2024-12-30 17:49 UTC, Luiz-Cruz requested changes
comentários acima

2025-01-03 00:52 UTC, andressa-mb commented on test/orders.test.js
Tive que colocar o orders dentro do escopo de teste pois o Jest não acessa variáveis globais. Senão deixasse dentro do escopo dava erro, ai é isso ou deixar num outro arquivo mesmo pelo que vi.

2025-01-06 13:41 UTC, Luiz-Cruz commented on test/orders.test.js
tenta dar uma olhada nesse exemplo: https://github.com/Jpgomes06/social-network/blob/main/tests/service/userService.test.js

2025-01-06 13:42 UTC, Luiz-Cruz requested changes
https://github.com/Jpgomes06/social-network/blob/main/tests/service/userService.test.js

2025-01-14 04:03 UTC, Luiz-Cruz approved these changes

2025-01-14 13:38 UTC, merged