Improvements in Feature/crud order
andressa-mb/ecommerce-api pull request #3
Opened 2024-10-14 00:29 UTC by andressa-mb

2024-10-15 13:41 UTC, Luiz-Cruz requested changes
deixei comentários acima

2024-10-15 13:41 UTC, Luiz-Cruz commented on api.js
> +const httpStatus = require('./http-status');
const express = require('express');
const mongoose = require('mongoose');
const dotenv = require('dotenv');
const orderModel = require('./order-model');
const httpStatus = require('./http-status');

const app = express();
const port = 3000;

2024-10-15 13:41 UTC, Luiz-Cruz commented on http-status.js
> +}
poderia adicionar uma linha ao final do arquivo por favor?
motivo: https://pt.stackoverflow.com/questions/272449/por-que-inserir-uma-linha-em-branco-no-final-do-c%C3%B3digo

2024-10-15 17:20 UTC, andressa-mb reviewed
Mudanças para verificar.

2024-10-17 03:34 UTC, Luiz-Cruz approved these changes

2024-10-17 14:56 UTC, merged